### ISSUE TITLE
I can't install binrec, it seems there is a HTTP connection error when executing "pipenv lock --dev"

### ISSUE THREAD

**Issue by danxinzhujian** [trailofbits/binrec-tob#42]
`test -f Pipfile.lock || pipenv lock --dev
Locking [dev-packages] dependencies…
ts/packages/urllib3/connectionpool.py", line 592, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/packages/urllib3/connectionpool.py", line 355, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/packages/urllib3/connectionpool.py", line 315, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pipenv/resolver.py", line 82, in <module>
    main()
  File "/usr/lib/python3/dist-packages/pipenv/resolver.py", line 66, in main
    results = resolve(
  File "/usr/lib/python3/dist-packages/pipenv/resolver.py", line 56, in resolve
    return pipenv.utils.resolve_deps(
  File "/usr/lib/python3/dist-packages/pipenv/utils.py", line 469, in resolve_deps
    r = requests.get(
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=10)

error: Recipe `_binrec-init` failed on line 55 with exit code 1
`

**Comment by risuxx** [comment]
I got the same err

**Comment by michaelbrownuc** [comment]
Looks like a network issue, does the environment you are building the tool in have access to the internet?
